spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:transferencia_bancaria}
    username: ${DB_USER:miguel}
    password: ${DB_PASSWORD:123}
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080